### ISSUE TITLE
Missing flow of change arrow 

### ISSUE THREAD

**Issue by conjurer-rich** [malparty/miro-team-topologies#1]
An important addition to a TT diagram is the inclusion of the flow of change arrow so that viewers understand the intended flow through the teams.

https://github.com/TeamTopologies/Team-Shape-Templates#available-team-shapes

Would it be possible to include this?

**Comment by malparty** [comment]
good remark! I'll plan that for next week (ETA Friday as I'm a bit busy until next Tuesday). 
Thanks a lot! :)
