### ISSUE TITLE
Need to update to support the Miro V2 Developer platform

### ISSUE THREAD

**Issue by conjurer-rich** [malparty/miro-team-topologies#10]
As per the email from Miro, we need to determine if this will affect this plugin and update it accordingly if required.

"Hello,

Earlier this year, we announced the Beta version of our Miro Developer Platform v2. Thanks to feedback from developers like you, we have continued to improve the v2 platform in preparation for a full launch.

Today we are announcing that the new APIs and SDK are ready for General Availability, with updated tools, libraries, and documentation available to help you develop on Miro.

[Learn about the new platform](https://email.miro.com/e/c/eyJlbWFpbF9pZCI6IlJNRF9Bd01BQVlDM2Z5UnVTNGs0eDZwVl9RNUszUT09IiwiaHJlZiI6Imh0dHBzOi8vZGV2ZWxvcGVycy5taXJvLmNvbS8_dXRtX2NhbXBhaWduPXBsX2xhdW5jaF9kZXZfMTEwNTIwMjJcdTAwMjZ1dG1fY29udGVudD1wbF9sYXVuY2hfZGV2XzExMDUyMDIyXHUwMDI2dXRtX21lZGl1bT1lbWFpbF9hY3Rpb25cdTAwMjZ1dG1fc291cmNlPWN1c3RvbWVyLmlvIiwiaW50ZXJuYWwiOiJjMGZmMDNlYjA4OWY5ZDAxYjE5Mzk4MTAiLCJsaW5rX2lkIjo4NzQ3NjE5fQ/fea331880c9865b075f16e4aa6f47385283af4980e6a08fe39ef325a37d85bb4) →
With the updated Miro Developer Platform now recommended for application development, we plan to retire v1 by the end of 2022.

For support in migrating your existing v1 platform apps to the v2 platform, please check out [our migration guides](https://email.miro.com/e/c/eyJlbWFpbF9pZCI6IlJNRF9Bd01BQVlDM2Z5UnVTNGs0eDZwVl9RNUszUT09IiwiaHJlZiI6Imh0dHBzOi8vZGV2ZWxvcGVycy5taXJvLmNvbS9kb2NzL21pZ3JhdGUtZnJvbS12MS10by12Mj91dG1fY2FtcGFpZ249cGxfbGF1bmNoX2Rldl8xMTA1MjAyMlx1MDAyNnV0bV9jb250ZW50PXBsX2xhdW5jaF9kZXZfMTEwNTIwMjJcdTAwMjZ1dG1fbWVkaXVtPWVtYWlsX2FjdGlvblx1MDAyNnV0bV9zb3VyY2U9Y3VzdG9tZXIuaW8iLCJpbnRlcm5hbCI6ImMwZmYwM2ViMDg5ZjlkMDFiMTkzOTgxMCIsImxpbmtfaWQiOjg3NDc2MjB9/005635df76e6513969f3f28085c41283f7feebca2a9d70022b35e30b823c4e65), and share your questions with the Miro Developer Community.

Thank You!
The Miro Developer Platform Team"

Need to determine whether this will affect the Miro tool and perform appropriate actions.

**Comment by conjurer-rich** [comment]
Hey @malparty I hope you are well, is this something you could look into?

**Comment by malparty** [comment]
I think I can handle it in the coming weeks ;-) 
I'll let you know if there is any blocker.

**Comment by conjurer-rich** [comment]
Awesome thanks
