### ISSUE TITLE
Add "Undefined Team" as Supplementary Team Type shape 

### ISSUE THREAD

**Issue by conjurer-rich** [malparty/miro-team-topologies#6]
A new Undefined Team Type shape has recently been introduced to enable a consistent representation of teams that have yet to be classified as one of the fundamental team types.

The Miro plugin will need to be updated to include this. See https://github.com/TeamTopologies/Team-Shape-Templates for more details.

**Comment by conjurer-rich** [comment]
@malparty is this something you could help with?

**Comment by malparty** [comment]
It shouldn't be a big change 🤔 
I'll try to have a look at it this week @conjurer-rich ;-)

**Comment by malparty** [comment]
@conjurer-rich @manupaisable @matthewskelton 
What would be the best location for this new "group" of elements? 🤔 

![image](https://user-images.githubusercontent.com/77609814/152106083-36662670-8715-417e-b52f-e4a8e203b2cc.png)


Should I put it right after the Team Types? (as in the picture above). 
Or is it better at the end of the existing groups (Team Types, Team Interactions & Flow of Change)? :) 

(note the PR I've just opened is still a DRAFT and not completed at all — I'll notify you once ready for review)

**Update:** PR ready for review ;-) And happy new year 🐯

**Comment by conjurer-rich** [comment]
Hey, many thanks for this. What about something like this?

![image](https://user-images.githubusercontent.com/73941040/152134690-d7d62ebc-0003-4958-a71a-78991889ae30.png)

I'll take a look at the PR thanks
